// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserProfile.API.DBContexts;

namespace UserProfile.API.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserProfile.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Birthday");

                    b.Property<string>("City");

                    b.Property<string>("CompanyName");

                    b.Property<string>("County");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsUserGarage");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("ProfileDescription");

                    b.Property<string>("Street");

                    b.Property<string>("URL");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("UsersProfiles");

                    b.HasData(
                        new { Id = 1, City = "Sligo", CompanyName = "GarageFix", County = "Sligo", Email = "GarageFix@email.com", FirstName = "John", IsUserGarage = true, LastName = "Smyth", PhoneNumber = "0888555666", ProfileDescription = "the best service", Street = "39 Connor Street", URL = "www.GarageFix.test", ZipCode = "2GRE1" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
