// <auto-generated />
using System;
using AdvertFix.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvertFix.Data.Migrations
{
    [DbContext(typeof(AdvertFixContext))]
    [Migration("20210131131720_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdvertFix.Domain.Models.Advert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CarModel");

                    b.Property<string>("City");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Adverts");
                });

            modelBuilder.Entity("AdvertFix.Domain.Models.Advertiser", b =>
                {
                    b.Property<int>("AdvertiserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AdvertId");

                    b.Property<string>("AdvertiserName");

                    b.Property<string>("Email");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("AdvertiserId");

                    b.HasIndex("AdvertId");

                    b.ToTable("Advertisers");
                });

            modelBuilder.Entity("AdvertFix.Domain.Models.Photo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AdvertId");

                    b.Property<bool>("IsMain");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("AdvertFix.Domain.Models.Advertiser", b =>
                {
                    b.HasOne("AdvertFix.Domain.Models.Advert", "AdvertFix")
                        .WithMany("UserAdverts")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AdvertFix.Domain.Models.Photo", b =>
                {
                    b.HasOne("AdvertFix.Domain.Models.Advert")
                        .WithMany("Photos")
                        .HasForeignKey("AdvertId");
                });
#pragma warning restore 612, 618
        }
    }
}
