// <auto-generated />
using System;
using AdvertFix.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvertFix.Data.Migrations
{
    [DbContext(typeof(AdvertFixContext))]
    partial class AdvertFixContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdvertFix.Domain.Models.Advert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdvertiserId");

                    b.Property<string>("CarModel");

                    b.Property<string>("City");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserId");

                    b.ToTable("Adverts");
                });

            modelBuilder.Entity("AdvertFix.Domain.Models.Advertiser", b =>
                {
                    b.Property<int>("AdvertiserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdvertiserName");

                    b.Property<string>("Email");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("AdvertiserId");

                    b.ToTable("Advertisers");
                });

            modelBuilder.Entity("AdvertFix.Domain.Models.Photo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsMain");

                    b.Property<int?>("PhotoAdvertId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("PhotoAdvertId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("AdvertFix.Domain.Models.Advert", b =>
                {
                    b.HasOne("AdvertFix.Domain.Models.Advertiser", "Advertiser")
                        .WithMany()
                        .HasForeignKey("AdvertiserId");
                });

            modelBuilder.Entity("AdvertFix.Domain.Models.Photo", b =>
                {
                    b.HasOne("AdvertFix.Domain.Models.Advert", "PhotoAdvert")
                        .WithMany("Photos")
                        .HasForeignKey("PhotoAdvertId");
                });
#pragma warning restore 612, 618
        }
    }
}
